/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.domainmodel.DomainmodelPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
