/**
 * generated by Xtext 2.25.0
 */
package org.example.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
